package wui

import "github.com/ejuju/go-utils/pkg/cssg"

func AlignContent(v string) cssg.Decl             { return cssg.Decl{"align-content", v} }
func AlignItems(v string) cssg.Decl               { return cssg.Decl{"align-items", v} }
func AlignSelf(v string) cssg.Decl                { return cssg.Decl{"align-self", v} }
func All(v string) cssg.Decl                      { return cssg.Decl{"all", v} }
func Animation(v string) cssg.Decl                { return cssg.Decl{"animation", v} }
func AnimationDelay(v string) cssg.Decl           { return cssg.Decl{"animation-delay", v} }
func AnimationDirection(v string) cssg.Decl       { return cssg.Decl{"animation-direction", v} }
func AnimationDuration(v string) cssg.Decl        { return cssg.Decl{"animation-duration", v} }
func AnimationFillMode(v string) cssg.Decl        { return cssg.Decl{"animation-fill-mode", v} }
func AnimationIterationCount(v string) cssg.Decl  { return cssg.Decl{"animation-iteration-count", v} }
func AnimationName(v string) cssg.Decl            { return cssg.Decl{"animation-name", v} }
func AnimationPlayState(v string) cssg.Decl       { return cssg.Decl{"animation-play-state", v} }
func AnimationTimingFunction(v string) cssg.Decl  { return cssg.Decl{"animation-timing-function", v} }
func BackfaceVisibility(v string) cssg.Decl       { return cssg.Decl{"backface-visibility", v} }
func Background(v string) cssg.Decl               { return cssg.Decl{"background", v} }
func BackgroundAttachment(v string) cssg.Decl     { return cssg.Decl{"background-attachment", v} }
func BackgroundBlendMode(v string) cssg.Decl      { return cssg.Decl{"background-blend-mode", v} }
func BackgroundClip(v string) cssg.Decl           { return cssg.Decl{"background-clip", v} }
func BackgroundColor(v string) cssg.Decl          { return cssg.Decl{"background-color", v} }
func BackgroundImage(v string) cssg.Decl          { return cssg.Decl{"background-image", v} }
func BackgroundOrigin(v string) cssg.Decl         { return cssg.Decl{"background-origin", v} }
func BackgroundPosition(v string) cssg.Decl       { return cssg.Decl{"background-position", v} }
func BackgroundRepeat(v string) cssg.Decl         { return cssg.Decl{"background-repeat", v} }
func BackgroundSize(v string) cssg.Decl           { return cssg.Decl{"background-size", v} }
func Border(v string) cssg.Decl                   { return cssg.Decl{"border", v} }
func BorderBottom(v string) cssg.Decl             { return cssg.Decl{"border-bottom", v} }
func BorderBottomColor(v string) cssg.Decl        { return cssg.Decl{"border-bottom-color", v} }
func BorderBottomLeftRadius(v string) cssg.Decl   { return cssg.Decl{"border-bottom-left-radius", v} }
func BorderBottomRightRadius(v string) cssg.Decl  { return cssg.Decl{"border-bottom-right-radius", v} }
func BorderBottomStyle(v string) cssg.Decl        { return cssg.Decl{"border-bottom-style", v} }
func BorderBottomWidth(v string) cssg.Decl        { return cssg.Decl{"border-bottom-width", v} }
func BorderCollapse(v string) cssg.Decl           { return cssg.Decl{"border-collapse", v} }
func BorderColor(v string) cssg.Decl              { return cssg.Decl{"border-color", v} }
func BorderImage(v string) cssg.Decl              { return cssg.Decl{"border-image", v} }
func BorderImageOutset(v string) cssg.Decl        { return cssg.Decl{"border-image-outset", v} }
func BorderImageRepeat(v string) cssg.Decl        { return cssg.Decl{"border-image-repeat", v} }
func BorderImageSlice(v string) cssg.Decl         { return cssg.Decl{"border-image-slice", v} }
func BorderImageSource(v string) cssg.Decl        { return cssg.Decl{"border-image-source", v} }
func BorderImageWidth(v string) cssg.Decl         { return cssg.Decl{"border-image-width", v} }
func BorderLeft(v string) cssg.Decl               { return cssg.Decl{"border-left", v} }
func BorderLeftColor(v string) cssg.Decl          { return cssg.Decl{"border-left-color", v} }
func BorderLeftStyle(v string) cssg.Decl          { return cssg.Decl{"border-left-style", v} }
func BorderLeftWidth(v string) cssg.Decl          { return cssg.Decl{"border-left-width", v} }
func BorderRadius(v string) cssg.Decl             { return cssg.Decl{"border-radius", v} }
func BorderRight(v string) cssg.Decl              { return cssg.Decl{"border-right", v} }
func BorderRightColor(v string) cssg.Decl         { return cssg.Decl{"border-right-color", v} }
func BorderRightStyle(v string) cssg.Decl         { return cssg.Decl{"border-right-style", v} }
func BorderRightWidth(v string) cssg.Decl         { return cssg.Decl{"border-right-width", v} }
func BorderSpacing(v string) cssg.Decl            { return cssg.Decl{"border-spacing", v} }
func BorderStyle(v string) cssg.Decl              { return cssg.Decl{"border-style", v} }
func BorderTop(v string) cssg.Decl                { return cssg.Decl{"border-top", v} }
func BorderTopColor(v string) cssg.Decl           { return cssg.Decl{"border-top-color", v} }
func BorderTopLeftRadius(v string) cssg.Decl      { return cssg.Decl{"border-top-left-radius", v} }
func BorderTopRightRadius(v string) cssg.Decl     { return cssg.Decl{"border-top-right-radius", v} }
func BorderTopStyle(v string) cssg.Decl           { return cssg.Decl{"border-top-style", v} }
func BorderTopWidth(v string) cssg.Decl           { return cssg.Decl{"border-top-width", v} }
func BorderWidth(v string) cssg.Decl              { return cssg.Decl{"border-width", v} }
func Bottom(v string) cssg.Decl                   { return cssg.Decl{"bottom", v} }
func BoxShadow(v string) cssg.Decl                { return cssg.Decl{"box-shadow", v} }
func BoxSizing(v string) cssg.Decl                { return cssg.Decl{"box-sizing", v} }
func CaptionSide(v string) cssg.Decl              { return cssg.Decl{"caption-side", v} }
func CaretColor(v string) cssg.Decl               { return cssg.Decl{"caret-color", v} }
func Clear(v string) cssg.Decl                    { return cssg.Decl{"clear", v} }
func Clip(v string) cssg.Decl                     { return cssg.Decl{"clip", v} }
func ClipPath(v string) cssg.Decl                 { return cssg.Decl{"clip-path", v} }
func Color(v string) cssg.Decl                    { return cssg.Decl{"color", v} }
func ColumnCount(v string) cssg.Decl              { return cssg.Decl{"column-count", v} }
func ColumnFill(v string) cssg.Decl               { return cssg.Decl{"column-fill", v} }
func ColumnGap(v string) cssg.Decl                { return cssg.Decl{"column-gap", v} }
func ColumnRule(v string) cssg.Decl               { return cssg.Decl{"column-rule", v} }
func ColumnRuleColor(v string) cssg.Decl          { return cssg.Decl{"column-rule-color", v} }
func ColumnRuleStyle(v string) cssg.Decl          { return cssg.Decl{"column-rule-style", v} }
func ColumnRuleWidth(v string) cssg.Decl          { return cssg.Decl{"column-rule-width", v} }
func ColumnSpan(v string) cssg.Decl               { return cssg.Decl{"column-span", v} }
func ColumnWidth(v string) cssg.Decl              { return cssg.Decl{"column-width", v} }
func Columns(v string) cssg.Decl                  { return cssg.Decl{"columns", v} }
func Content(v string) cssg.Decl                  { return cssg.Decl{"content", v} }
func CounterIncrement(v string) cssg.Decl         { return cssg.Decl{"counter-increment", v} }
func CounterReset(v string) cssg.Decl             { return cssg.Decl{"counter-reset", v} }
func Cursor(v string) cssg.Decl                   { return cssg.Decl{"cursor", v} }
func Direction(v string) cssg.Decl                { return cssg.Decl{"direction", v} }
func Display(v string) cssg.Decl                  { return cssg.Decl{"display", v} }
func EmptyCells(v string) cssg.Decl               { return cssg.Decl{"empty-cells", v} }
func Filter(v string) cssg.Decl                   { return cssg.Decl{"filter", v} }
func Flex(v string) cssg.Decl                     { return cssg.Decl{"flex", v} }
func FlexBasis(v string) cssg.Decl                { return cssg.Decl{"flex-basis", v} }
func FlexDirection(v string) cssg.Decl            { return cssg.Decl{"flex-direction", v} }
func FlexFlow(v string) cssg.Decl                 { return cssg.Decl{"flex-flow", v} }
func FlexGrow(v string) cssg.Decl                 { return cssg.Decl{"flex-grow", v} }
func FlexShrink(v string) cssg.Decl               { return cssg.Decl{"flex-shrink", v} }
func FlexWrap(v string) cssg.Decl                 { return cssg.Decl{"flex-wrap", v} }
func Float(v string) cssg.Decl                    { return cssg.Decl{"float", v} }
func Font(v string) cssg.Decl                     { return cssg.Decl{"font", v} }
func FontFamily(v string) cssg.Decl               { return cssg.Decl{"font-family", v} }
func FontKerning(v string) cssg.Decl              { return cssg.Decl{"font-kerning", v} }
func FontSize(v string) cssg.Decl                 { return cssg.Decl{"font-size", v} }
func FontSizeAdjust(v string) cssg.Decl           { return cssg.Decl{"font-size-adjust", v} }
func FontStretch(v string) cssg.Decl              { return cssg.Decl{"font-stretch", v} }
func FontStyle(v string) cssg.Decl                { return cssg.Decl{"font-style", v} }
func FontVariant(v string) cssg.Decl              { return cssg.Decl{"font-variant", v} }
func FontWeight(v string) cssg.Decl               { return cssg.Decl{"font-weight", v} }
func Gap(v string) cssg.Decl                      { return cssg.Decl{"gap", v} }
func Grid(v string) cssg.Decl                     { return cssg.Decl{"grid", v} }
func GridArea(v string) cssg.Decl                 { return cssg.Decl{"grid-area", v} }
func GridAutoColumns(v string) cssg.Decl          { return cssg.Decl{"grid-auto-columns", v} }
func GridAutoFlow(v string) cssg.Decl             { return cssg.Decl{"grid-auto-flow", v} }
func GridAutoRows(v string) cssg.Decl             { return cssg.Decl{"grid-auto-rows", v} }
func GridColumn(v string) cssg.Decl               { return cssg.Decl{"grid-column", v} }
func GridColumnEnd(v string) cssg.Decl            { return cssg.Decl{"grid-column-end", v} }
func GridColumnGap(v string) cssg.Decl            { return cssg.Decl{"grid-column-gap", v} }
func GridColumnStart(v string) cssg.Decl          { return cssg.Decl{"grid-column-start", v} }
func GridGap(v string) cssg.Decl                  { return cssg.Decl{"grid-gap", v} }
func GridRow(v string) cssg.Decl                  { return cssg.Decl{"grid-row", v} }
func GridRowEnd(v string) cssg.Decl               { return cssg.Decl{"grid-row-end", v} }
func GridRowGap(v string) cssg.Decl               { return cssg.Decl{"grid-row-gap", v} }
func GridRowStart(v string) cssg.Decl             { return cssg.Decl{"grid-row-start", v} }
func GridTemplate(v string) cssg.Decl             { return cssg.Decl{"grid-template", v} }
func GridTemplateAreas(v string) cssg.Decl        { return cssg.Decl{"grid-template-areas", v} }
func GridTemplateColumns(v string) cssg.Decl      { return cssg.Decl{"grid-template-columns", v} }
func GridTemplateRows(v string) cssg.Decl         { return cssg.Decl{"grid-template-rows", v} }
func Height(v string) cssg.Decl                   { return cssg.Decl{"height", v} }
func Hyphens(v string) cssg.Decl                  { return cssg.Decl{"hyphens", v} }
func JustifyContent(v string) cssg.Decl           { return cssg.Decl{"justify-content", v} }
func Left(v string) cssg.Decl                     { return cssg.Decl{"left", v} }
func LetterSpacing(v string) cssg.Decl            { return cssg.Decl{"letter-spacing", v} }
func LineHeight(v string) cssg.Decl               { return cssg.Decl{"line-height", v} }
func ListStyle(v string) cssg.Decl                { return cssg.Decl{"list-style", v} }
func ListStyleImage(v string) cssg.Decl           { return cssg.Decl{"list-style-image", v} }
func ListStylePosition(v string) cssg.Decl        { return cssg.Decl{"list-style-position", v} }
func ListStyleType(v string) cssg.Decl            { return cssg.Decl{"list-style-type", v} }
func Margin(v string) cssg.Decl                   { return cssg.Decl{"margin", v} }
func MarginBottom(v string) cssg.Decl             { return cssg.Decl{"margin-bottom", v} }
func MarginLeft(v string) cssg.Decl               { return cssg.Decl{"margin-left", v} }
func MarginRight(v string) cssg.Decl              { return cssg.Decl{"margin-right", v} }
func MarginTop(v string) cssg.Decl                { return cssg.Decl{"margin-top", v} }
func MaxHeight(v string) cssg.Decl                { return cssg.Decl{"max-height", v} }
func MaxWidth(v string) cssg.Decl                 { return cssg.Decl{"max-width", v} }
func MinHeight(v string) cssg.Decl                { return cssg.Decl{"min-height", v} }
func MinWidth(v string) cssg.Decl                 { return cssg.Decl{"min-width", v} }
func ObjectFit(v string) cssg.Decl                { return cssg.Decl{"object-fit", v} }
func ObjectPosition(v string) cssg.Decl           { return cssg.Decl{"object-position", v} }
func Opacity(v string) cssg.Decl                  { return cssg.Decl{"opacity", v} }
func Order(v string) cssg.Decl                    { return cssg.Decl{"order", v} }
func Outline(v string) cssg.Decl                  { return cssg.Decl{"outline", v} }
func OutlineColor(v string) cssg.Decl             { return cssg.Decl{"outline-color", v} }
func OutlineOffset(v string) cssg.Decl            { return cssg.Decl{"outline-offset", v} }
func OutlineStyle(v string) cssg.Decl             { return cssg.Decl{"outline-style", v} }
func OutlineWidth(v string) cssg.Decl             { return cssg.Decl{"outline-width", v} }
func Overflow(v string) cssg.Decl                 { return cssg.Decl{"overflow", v} }
func OverflowX(v string) cssg.Decl                { return cssg.Decl{"overflow-x", v} }
func OverflowY(v string) cssg.Decl                { return cssg.Decl{"overflow-y", v} }
func Padding(v string) cssg.Decl                  { return cssg.Decl{"padding", v} }
func PaddingBottom(v string) cssg.Decl            { return cssg.Decl{"padding-bottom", v} }
func PaddingLeft(v string) cssg.Decl              { return cssg.Decl{"padding-left", v} }
func PaddingRight(v string) cssg.Decl             { return cssg.Decl{"padding-right", v} }
func PaddingTop(v string) cssg.Decl               { return cssg.Decl{"padding-top", v} }
func PageBreakAfter(v string) cssg.Decl           { return cssg.Decl{"page-break-after", v} }
func PageBreakBefore(v string) cssg.Decl          { return cssg.Decl{"page-break-before", v} }
func PageBreakInside(v string) cssg.Decl          { return cssg.Decl{"page-break-inside", v} }
func Perspective(v string) cssg.Decl              { return cssg.Decl{"perspective", v} }
func PerspectiveOrigin(v string) cssg.Decl        { return cssg.Decl{"perspective-origin", v} }
func PointerEvents(v string) cssg.Decl            { return cssg.Decl{"pointer-events", v} }
func Position(v string) cssg.Decl                 { return cssg.Decl{"position", v} }
func Quotes(v string) cssg.Decl                   { return cssg.Decl{"quotes", v} }
func Right(v string) cssg.Decl                    { return cssg.Decl{"right", v} }
func RowGap(v string) cssg.Decl                   { return cssg.Decl{"row-gap", v} }
func ScrollBehavior(v string) cssg.Decl           { return cssg.Decl{"scroll-behavior", v} }
func TableLayout(v string) cssg.Decl              { return cssg.Decl{"table-layout", v} }
func TextAlign(v string) cssg.Decl                { return cssg.Decl{"text-align", v} }
func TextAlignLast(v string) cssg.Decl            { return cssg.Decl{"text-align-last", v} }
func TextDecoration(v string) cssg.Decl           { return cssg.Decl{"text-decoration", v} }
func TextDecorationColor(v string) cssg.Decl      { return cssg.Decl{"text-decoration-color", v} }
func TextDecorationLine(v string) cssg.Decl       { return cssg.Decl{"text-decoration-line", v} }
func TextDecorationStyle(v string) cssg.Decl      { return cssg.Decl{"text-decoration-style", v} }
func TextIndent(v string) cssg.Decl               { return cssg.Decl{"text-indent", v} }
func TextJustify(v string) cssg.Decl              { return cssg.Decl{"text-justify", v} }
func TextOverflow(v string) cssg.Decl             { return cssg.Decl{"text-overflow", v} }
func TextShadow(v string) cssg.Decl               { return cssg.Decl{"text-shadow", v} }
func TextTransform(v string) cssg.Decl            { return cssg.Decl{"text-transform", v} }
func Top(v string) cssg.Decl                      { return cssg.Decl{"top", v} }
func Transform(v string) cssg.Decl                { return cssg.Decl{"transform", v} }
func TransformOrigin(v string) cssg.Decl          { return cssg.Decl{"transform-origin", v} }
func TransformStyle(v string) cssg.Decl           { return cssg.Decl{"transform-style", v} }
func Transition(v string) cssg.Decl               { return cssg.Decl{"transition", v} }
func TransitionDelay(v string) cssg.Decl          { return cssg.Decl{"transition-delay", v} }
func TransitionDuration(v string) cssg.Decl       { return cssg.Decl{"transition-duration", v} }
func TransitionProperty(v string) cssg.Decl       { return cssg.Decl{"transition-property", v} }
func TransitionTimingFunction(v string) cssg.Decl { return cssg.Decl{"transition-timing-function", v} }
func UserSelect(v string) cssg.Decl               { return cssg.Decl{"user-select", v} }
func VerticalAlign(v string) cssg.Decl            { return cssg.Decl{"vertical-align", v} }
func Visibility(v string) cssg.Decl               { return cssg.Decl{"visibility", v} }
func WhiteSpace(v string) cssg.Decl               { return cssg.Decl{"white-space", v} }
func Width(v string) cssg.Decl                    { return cssg.Decl{"width", v} }
func WordBreak(v string) cssg.Decl                { return cssg.Decl{"word-break", v} }
func Wordspacing(v string) cssg.Decl              { return cssg.Decl{"word-spacing", v} }
func WordWrap(v string) cssg.Decl                 { return cssg.Decl{"word-wrap", v} }
func WritingMode(v string) cssg.Decl              { return cssg.Decl{"writing-mode", v} }
func ZIndex(v string) cssg.Decl                   { return cssg.Decl{"z-index", v} }
