package wui

import "github.com/ejuju/go-utils/pkg/htmlg"

func A(opts ...htmlg.Modifier) *htmlg.Element          { return htmlg.Create("a", opts...) }
func Address(opts ...htmlg.Modifier) *htmlg.Element    { return htmlg.Create("address", opts...) }
func Abbr(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("abbr", opts...) }
func Article(opts ...htmlg.Modifier) *htmlg.Element    { return htmlg.Create("article", opts...) }
func Aside(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("aside", opts...) }
func Area(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("area", opts...) }
func Audio(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("audio", opts...) }
func B(opts ...htmlg.Modifier) *htmlg.Element          { return htmlg.Create("base", opts...) }
func Base(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("base", opts...) }
func Bdi(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("bdi", opts...) }
func Bdo(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("bdo", opts...) }
func Blockquote(opts ...htmlg.Modifier) *htmlg.Element { return htmlg.Create("blockquote", opts...) }
func Body(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("body", opts...) }
func Br(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("br", opts...) }
func Button(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("button", opts...) }
func Cite(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("cite", opts...) }
func Col(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("col", opts...) }
func Code(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("code", opts...) }
func Data(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("data", opts...) }
func Dd(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("dd", opts...) }
func Div(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("div", opts...) }
func Dl(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("dl", opts...) }
func Dfn(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("dfn", opts...) }
func Dt(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("dt", opts...) }
func Em(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("em", opts...) }
func Embed(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("embed", opts...) }
func Footer(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("footer", opts...) }
func Form(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("form", opts...) }
func Figcaption(opts ...htmlg.Modifier) *htmlg.Element { return htmlg.Create("figcaption", opts...) }
func Figure(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("figure", opts...) }
func H1(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("h1", opts...) }
func H2(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("h2", opts...) }
func H3(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("h3", opts...) }
func H4(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("h4", opts...) }
func H5(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("h5", opts...) }
func H6(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("h6", opts...) }
func Hgroup(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("hgroup", opts...) }
func HTML(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("html", opts...) }
func Head(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("head", opts...) }
func Header(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("header", opts...) }
func Hr(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("hr", opts...) }
func I(opts ...htmlg.Modifier) *htmlg.Element          { return htmlg.Create("i", opts...) }
func Iframe(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("iframe", opts...) }
func Img(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("img", opts...) }
func Input(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("input", opts...) }
func Kbd(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("kbd", opts...) }
func Label(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("label", opts...) }
func Legend(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("legend", opts...) }
func Link(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("link", opts...) }
func Li(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("li", opts...) }
func Main(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("main", opts...) }
func Map(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("map", opts...) }
func Math(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("math", opts...) }
func Mark(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("mark", opts...) }
func Meta(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("meta", opts...) }
func Menu(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("menu", opts...) }
func Nav(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("nav", opts...) }
func Ol(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("ol", opts...) }
func Object(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("object", opts...) }
func P(opts ...htmlg.Modifier) *htmlg.Element          { return htmlg.Create("p", opts...) }
func Picture(opts ...htmlg.Modifier) *htmlg.Element    { return htmlg.Create("picture", opts...) }
func Portal(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("portal", opts...) }
func Pre(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("pre", opts...) }
func Q(opts ...htmlg.Modifier) *htmlg.Element          { return htmlg.Create("q", opts...) }
func U(opts ...htmlg.Modifier) *htmlg.Element          { return htmlg.Create("u", opts...) }
func Ul(opts ...htmlg.Modifier) *htmlg.Element         { return htmlg.Create("ul", opts...) }
func S(opts ...htmlg.Modifier) *htmlg.Element          { return htmlg.Create("s", opts...) }
func Samp(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("samp", opts...) }
func Source(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("source", opts...) }
func Section(opts ...htmlg.Modifier) *htmlg.Element    { return htmlg.Create("section", opts...) }
func Small(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("small", opts...) }
func Span(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("span", opts...) }
func Style(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("style", opts...) }
func Script(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("script", opts...) }
func Strong(opts ...htmlg.Modifier) *htmlg.Element     { return htmlg.Create("strong", opts...) }
func Sub(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("sub", opts...) }
func Sup(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("sup", opts...) }
func Svg(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("svg", opts...) }
func Textarea(opts ...htmlg.Modifier) *htmlg.Element   { return htmlg.Create("textarea", opts...) }
func Time(opts ...htmlg.Modifier) *htmlg.Element       { return htmlg.Create("time", opts...) }
func Title(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("title", opts...) }
func Track(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("track", opts...) }
func Var(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("var", opts...) }
func Video(opts ...htmlg.Modifier) *htmlg.Element      { return htmlg.Create("video", opts...) }
func Wbr(opts ...htmlg.Modifier) *htmlg.Element        { return htmlg.Create("wbr", opts...) }

func AttrId(v string) [2]string              { return [2]string{"id", v} }
func AttrClass(v string) [2]string           { return [2]string{"class", v} }
func AttrStyle(v string) [2]string           { return [2]string{"style", v} }
func AttrData(v string) [2]string            { return [2]string{"data", v} }
func AttrHidden(v string) [2]string          { return [2]string{"hidden", v} }
func AttrTitle(v string) [2]string           { return [2]string{"title", v} }
func AttrTabindex(v string) [2]string        { return [2]string{"tabindex", v} }
func AttrLang(v string) [2]string            { return [2]string{"lang", v} }
func AttrDraggable(v string) [2]string       { return [2]string{"draggable", v} }
func AttrAccesskey(v string) [2]string       { return [2]string{"accesskey", v} }
func AttrInputmode(v string) [2]string       { return [2]string{"inputmode", v} }
func AttrSpellcheck(v string) [2]string      { return [2]string{"spellcheck", v} }
func AttrAutocapitalize(v string) [2]string  { return [2]string{"autocapitalize", v} }
func AttrContenteditable(v string) [2]string { return [2]string{"contenteditable", v} }
func AttrDir(v string) [2]string             { return [2]string{"dir", v} }
func AttrIs(v string) [2]string              { return [2]string{"is", v} }

func AttrAction(v string) [2]string      { return [2]string{"action", v} }
func AttrRel(v string) [2]string         { return [2]string{"rel", v} }
func AttrHref(v string) [2]string        { return [2]string{"href", v} }
func AttrContent(v string) [2]string     { return [2]string{"content", v} }
func AttrMethod(v string) [2]string      { return [2]string{"method", v} }
func AttrOnclick(v string) [2]string     { return [2]string{"onclick", v} }
func AttrName(v string) [2]string        { return [2]string{"name", v} }
func AttrType(v string) [2]string        { return [2]string{"type", v} }
func AttrValue(v string) [2]string       { return [2]string{"value", v} }
func AttrPlaceholder(v string) [2]string { return [2]string{"placeholder", v} }
func AttrAriaCurrent() [2]string         { return [2]string{"aria-current", ""} }
